### PR TITLE
Add functionality for changing FHIR Server in context for the current session and immediately prompt for changing the patient in context

### PR DESCRIPTION
**Pull request by zplata**
Issue: https://github.com/cds-hooks/sandbox/issues/19

Currently, the CDS Hooks Sandbox tool runs against the SMART Health IT FHIR server (DSTU2 open endpoint) by default. It would be great if we could allow the tool to run against other user-specified FHIR servers as well. This allows users to simulate CDS Hooks in different environments via other available FHIR servers, and test patients hosted in different FHIR servers as well.

This functionality is supported already by adding a `fhirServiceUrl` parameter with an encoded url to the existing sandbox URL. We can make this hidden functionality more face-up by adding a button in the header that opens a modal to allow users to change the existing FHIR server (similar to changing the patient in context). Before the tool accepts the user-specified FHIR server, the tool can do a quick check against the FHIR server's metadata endpoint to see if it is valid. Upon a successful switch to the new FHIR server, the user will immediately be prompted to change the patient in context. 

screen shot 2017-07-12 at 9 52 45 am
screen shot 2017-07-12 at 9 54 06 am
screen shot 2017-07-12 at 9 54 52 am

@kpshek 
@mjhenkes 
@kolkheang 
@shriniketsarkar 
@koushic
@koushic88

### CODE REVIEW

**Comment by kpshek** [comment]
@zplata - Is this deployed anywhere where I can check it out?

**Comment by mjhenkes** [comment]
If only we had a pull request builder that could deploy our PR's for us to test. 😜

**Comment by kpshek** [comment]
We'll have that tomorrow. 😄 🙌

**Comment by zplata** [comment]
@kpshek Until we get that up, I updated my personal fork with this change.
https://zplata.github.io/cds-hooks-sandbox/

**Comment by zplata** [comment]
@kpshek Thanks for finding that - fixed that issue and added an option on the modal to reset to the default FHIR server. It's deployed on my fork, so you can check it out again.

**Comment by kpshek** [comment]
@zplata - When I enter `foo` as  the URL, the JS makes a call to https://zplata.github.io/cds-hooks-sandbox/foo/metadata. We should be treating the input as a URL and not as a possible path on the current domain

**Comment by zplata** [comment]
@kpshek Fixed so that the user input is transformed into a URL if not one already.

**Pull request merged**
