### PR TITLE
Add option on toolbar to demo card render functionality. Allow developers to render a card in realtime via JSON they can edit in-app.

### PR DESCRIPTION
**Pull request by zplata**
Issue: https://github.com/cds-hooks/sandbox/issues/22

Currently, the only way to see a card render is through testing a CDS Service response in an EHR setting or in the Sandbox. It would be nice for developers to easily check what a card could potentially look like without having to alter a CDS Service response on their end. 

We can enable this through an added functionality that allows users to edit JSON in real-time and displaying a single card accordingly side-by-side. This would take over the current hook and FHIR view. The feature would enable developers to customize their own CDS Service responses easily by first testing what it would really look like. 

See deployment to test it out

@kpshek 
@mjhenkes 
@kolkheang 
@shriniketsarkar 
@koushic88

### CODE REVIEW

**Comment by zplata** [comment]
Not ready for review - still tweaking UI things and adding an error display. But try playing around with the new functionality and see if we need to add/change anything major.

**Comment by zplata** [comment]
Ready for review

**Comment by kpshek** [comment]
🐛 
1. Click *Card Demo*
2. Click ◀️ *Return to Hooks*

You never get back to the homepage. The button will always say "Return to Hooks" and you're now stuck on the 'Preview a Card with JSON' screen.

**Comment by zplata** [comment]
@kpshek Did you load the "unsafe scripts"

**Comment by kpshek** [comment]
> @kpshek Did you load the "unsafe scripts"

**Comment by zplata** [comment]
We probably won't run into this issue once we host the default CDS services elsewhere :)

**Pull request merged**
