### PR TITLE
Add validation checks for SMART links in cards to check if theyre appended with iss or launch parameters and display an error accordingly

### PR DESCRIPTION
**Pull request by zplata**
Issue: https://github.com/cds-hooks/sandbox/issues/58

Currently, SMART app links returned in cards will be opened in a new window, regardless of how the URL is formatted. In order for the Sandbox to help developers comply with the 1.0 spec, we should add validation upon clicking these links. This validation would ensure that these links are not appended with `iss` or `launch` parameters (as that is the job of the EHR, if launched securely). If the url returned by a CDS Service does happen to have those parameters appended to the launch url, an error modal will appear specifying that the url should just be the launch endpoint for an app. Additionally, in the modal, we should list these parameters and spell out why it should not be appended.

Along with this change, there's a fix to a bug where the SMART link may have the `fhirServiceUrl` and `patientId` parameters appended multiple times (if the render function for that class is called more than once). This doesn't necessarily affect the ability to navigate to that SMART link, but helps to de-duplicate the additional parameters being added on (in the case of an app being launched against an open endpoint).

@kpshek 
@kolkheang 
@mjhenkes 
@shriniketsarkar 
@koushic88

### CODE REVIEW

**Comment by kpshek** [comment]
A limitation of this error checking is that it only occurs when the user clicks the link. It would be better if we reported on any issues with the cards as we receive them from the CDS Service.

A simple implementation for this particular use case would be to simply output a console message stating that the SMART app link is malformed and not to render that particular link. We could throw up an error banner on the Sandbox page indicating an error was detected and to check the console for further details.

Thoughts @zplata?

**Comment by zplata** [comment]
@kpshek I think that change makes sense.

Might change that banner into a modal for now though, as the current state of how the UI is laid out makes for fairly larger CSS refactoring for a simple banner at the top (eventually this would be fixed in the tech debt uplift and can add a banner back in).

**Comment by zplata** [comment]
@kpshek Addressed above

**Comment by kpshek** [comment]
Thanks @zplata. Would it be possible to also do this check on the Card Demo page?

**Comment by zplata** [comment]
@kpshek Added with the new commit. I don't think we need to do console logging for the card demo, so we can throw an error panel up instead of rendering the card, similar to how we display an error panel for bad JSON syntax. And we can list the smart links that are malformed.

**Pull request closed without merging**
