### PR TITLE
Add vertically stacked panels to display CDS Service request and response with a log to console option.

### PR DESCRIPTION
**Pull request by zplata**
Issue: https://github.com/cds-hooks/sandbox/issues/21

Currently, the CDS Service request is being shown on the right hand side of the tool. This makes sense as it allows developers to see what is being sent to a CDS Service as it follows the current spec. Right now, this request takes up the entire right hand side panel of the tool. It would make more sense to move the request inside a collapsible bootstrap panel that a user can hide/display. 

This would in turn allow for extra screen real estate to display the CDS Service response. The response can also be placed inside a collapsible bootstrap panel that the user can hide/display. Displaying the CDS Service response can give developers a better picture of how the CDS Service/EHR exchange works and what is being sent. 

@kpshek 
@mjhenkes 
@shriniketsarkar 
@kolkheang 
@koushic88

### CODE REVIEW

**Comment by zplata** [comment]
This code isn't final - but wanted to get a starting point for ongoing discussion about how to display the CDS Service request/response effectively. Currently, it's just vertically stacked collapsibles. Upon expansion, a request/response may take up as much vertical space as needed.

I've deployed the functionality here if you want to check it out: https://zplata.github.io/cds-hooks-sandbox/

**Comment by kpshek** [comment]
Thanks @zplata! I like the stacked view quite a bit. We'll need to have some sort of picker to view the request/reply for each individual CDS Service. For instance, hook up at least two CDS Services in the Sandbox to see what I mean (I suspect you know this already).

Maybe when you click on a card it shows the associated request/response?

**Comment by kpshek** [comment]
> Maybe when you click on a card it shows the associated request/response?

Disregard this bad idea. If a CDS Service never returns a card, we'd never be able to see the request/response.

**Comment by zplata** [comment]
Updated the design and added a different context hide/display toggle. Now you can choose a service (dropdown) and see the request/response for the selection.
See here: https://zplata.github.io/cds-hooks-sandbox/

**Comment by zplata** [comment]
Updated to remove the console log option and just log to the console on every CDS Service selection change.

**Comment by kpshek** [comment]
Let us know when this is ready for review @zplata

**Comment by zplata** [comment]
@kpshek It's ready

**Pull request merged**
