### PR TITLE
Add travis yml file to coordinate automatic deploy to gh-pages branch from master

### PR DESCRIPTION
**Pull request by zplata**
Adding travis.yml file config to allow for auto-deploy to GH-pages from `master` builds. This will help remove the need for an extra PR to the `gh-pages` branch to deploy accepted changes into `master`.
 
@kpshek 
@mjhenkes

### CODE REVIEW

**Comment by koushic88** [comment]
+1

**Comment by zplata** [comment]
@kpshek I've removed that java dependency line from the travis config. Additionally, we have to keep a CNAME file in the build directory. Travis will force push and overwrite the history on the gh-pages branch with everything in the `/build` folder.

**Comment by kpshek** [comment]
@zplata - Can we split out the changes here into two separate concerns:

1. Build & deploy via TravisCI
2. Build Heroku Review Apps

We can issue a PR back to the upstream project for the TravisCI work. However, we'll keep the Heroku Review Apps work in our fork for the time being (I want to see how that works first -- especially related to free Heroku usage)

**Comment by zplata** [comment]
GITHUB_TOKEN environment variable has been configured as well for this repo (with `repo` scope)

**Comment by mjhenkes** [comment]
@kpshek The upstream project will need to have the GITHUB_TOKEN environment variable configured for it as well for the auto-deploy to GH pages to work.

**Comment by zplata** [comment]
@kpshek removed heroku file

**Pull request merged**
