### PR TITLE
Add heroku config file to enable heroku deployments on PR builds

### PR DESCRIPTION
**Pull request by zplata**
Currently, to check out a possible change for the CDS Hooks Sandbox tool, you have to pull down the changes from the compare branch and run the changes locally. Or someone has to deploy to an external `gh-pages` branch to show changes. It would be nice if the changes proposed in a PR can be deployed on a Heroku instance automatically. 

This would allow for ease of testing and better visibility for those looking to check out how changes affect the existing tool, and remove the need to deploy the changes on some external `gh-pages` site for testing purposes.

@kpshek 
@mjhenkes

### CODE REVIEW

**Comment by zplata** [comment]
I'll rebase this once the Travis stuff gets in so we don't have failing checks :)

**Comment by kpshek** [comment]
@zplata - Is this ready now?

**Comment by zplata** [comment]
@kpshek Just added a change to include express. Now it's ready

**Comment by zplata** [comment]
@kpshek took out those fields

**Pull request merged**
